server:
  port: 38080

spring:
  data:
    # redis 配置
    redis:
      # 地址
      host: 10.1.1.10
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 11
      # 密码
      password: "zgx1688"
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  datasource:
    url: jdbc:mysql://10.1.1.10:3306/ias?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: pl,okmijn
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5       # 连接池中的最小空闲连接数
      maximum-pool-size: 20  # 连接池的最大连接数
      idle-timeout: 30000    # 连接最大空闲时间（毫秒）
      max-lifetime: 1800000  # 连接的最大生命周期（毫秒），超时后自动关闭
      connection-timeout: 30000  # 连接超时时间（毫秒）
      pool-name: HikariCP-Pool  # 连接池名称

